### ISSUE TITLE
TreeUtils.getId(Repository, revision, path)

### ISSUE THREAD

**Issue by sonson** [kevinsawicki/gitective#2]
Hello,

first of all I want to say thank you for this great library. I am a (J)Git-beginner and didn't find any good JGit-examples until I found gitective. It really makes complicate things easier for me. :-)

One suggestion:

I have to list all files of a path. It would be very useful, if there is a `TreeUtils.getId(Repository, String revision, String path)`-method which returns an `ObjectId`. (I have found `BlobUtils.getId()`, but this only works for BLOB and not for TREEs.)

**Comment by kevinsawicki** [comment]
Thanks for the feedback, just pushed a new helper that returns the tree id for the given path and commit.

Will probably release a 0.9.5 over the weekend with this included.

**Comment by sonson** [comment]
Great, thank you very much!

**Comment by kevinsawicki** [comment]
This has been released in 0.9.6 which is available in Maven central.

Also added was [TreeUtils.visit](https://github.com/kevinsawicki/gitective/blob/master/org.gitective.core/src/main/java/org/gitective/core/TreeUtils.java#L406) which allows you to visit each tree entry recursively and know the name, parent path, SHA-1, and mode of each entry being visited.
